## Site settings
title: GDG Braga
title_min: GDGBRAGA
email:  mail@gdgbraga.xyz
description: > # this means to ignore newlines until "baseurl:"
 Google Developer Group Braga.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gdgbraga.github.io" # the base hostname & protocol for your site
url_dev: "http://localhost:4000"
twitter_username: gdgbraga
github_username:  GDGBraga

# Build settings
markdown: kramdown
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

pages:
  - title: Home
    url: /
  - title: Events
    url: /event
  - title: Team
    url: /team


exclude: ['package.json', '_src', 'node_modules', 'vendor/bundle/ruby']
